version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "investing-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iv40ea5q5g7g"
s3_prefix = "investing-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
